logging:
   level: trace

# logging.level:
#    org.springframework: ERROR
#    org.hibernate.SQL: ERROR

server:
  port: 8080
  address: 0.0.0.0


spring:
  datasource:
    platform: h2
    url: "jdbc:h2:mem:"
  jpa:
    hibernate:
      ddl-auto: create-drop
  jmx:
    enabled: true
    default-domain: oneops
  jackson.serialization:
    INDENT_OUTPUT: true


banner:
  location: classpath:oneops-banner.txt







