logging:
   level: trace

# logging.level:
#    org.springframework: ERROR
#    org.hibernate.SQL: ERROR

server:
  port: 8080
  address: 0.0.0.0
  compression:
    enabled: true


spring:
  datasource:
    platform: h2
    url: "jdbc:h2:mem:"
  jpa:
    hibernate:
      ddl-auto: create-drop
  jmx:
    enabled: true
    default-domain: oneops
  jackson.serialization:
    INDENT_OUTPUT: true

management:
  shell.auth.simple.user:
    name: oneops
    password: oneops
  context-path: /admin

endpoints:
  env:
    enabled: false
  beans:
    enabled: false

info:
  build:
    name: ${name}
    description: ${description}
    version: ${version}
    spring-boot-version: ${springBootVersion}
    kotlin-version: ${kotlinVersion}
    java: \${java.version}
    java-vendor: \${java.vendor}
    os-name: \${os.name}
    os-arch: \${os.arch}
    os-version: \${os.version}

banner:
  location: classpath:oneops-banner.txt








